// Mocks generated by Mockito 5.4.6 from annotations
// in task_four/test/mocks/map_view_model_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:latlong2/latlong.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:task_four/presentation/viewmodels/map_view.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MapViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapViewModel extends _i1.Mock implements _i2.MapViewModel {
  MockMapViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.LatLng> get waypoints =>
      (super.noSuchMethod(
            Invocation.getter(#waypoints),
            returnValue: <_i3.LatLng>[],
          )
          as List<_i3.LatLng>);

  @override
  List<_i3.LatLng> get routePoints =>
      (super.noSuchMethod(
            Invocation.getter(#routePoints),
            returnValue: <_i3.LatLng>[],
          )
          as List<_i3.LatLng>);

  @override
  double get distance =>
      (super.noSuchMethod(Invocation.getter(#distance), returnValue: 0.0)
          as double);

  @override
  double get duration =>
      (super.noSuchMethod(Invocation.getter(#duration), returnValue: 0.0)
          as double);

  @override
  _i2.CameraMode get cameraMode =>
      (super.noSuchMethod(
            Invocation.getter(#cameraMode),
            returnValue: _i2.CameraMode.free,
          )
          as _i2.CameraMode);

  @override
  set waypoints(List<_i3.LatLng>? value) => super.noSuchMethod(
    Invocation.setter(#waypoints, value),
    returnValueForMissingStub: null,
  );

  @override
  set routePoints(List<_i3.LatLng>? value) => super.noSuchMethod(
    Invocation.setter(#routePoints, value),
    returnValueForMissingStub: null,
  );

  @override
  set distance(double? value) => super.noSuchMethod(
    Invocation.setter(#distance, value),
    returnValueForMissingStub: null,
  );

  @override
  set duration(double? value) => super.noSuchMethod(
    Invocation.setter(#duration, value),
    returnValueForMissingStub: null,
  );

  @override
  set cameraMode(_i2.CameraMode? value) => super.noSuchMethod(
    Invocation.setter(#cameraMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchedLocation(_i3.LatLng? value) => super.noSuchMethod(
    Invocation.setter(#searchedLocation, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentLocation, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addWaypoint(_i3.LatLng? point) => super.noSuchMethod(
    Invocation.method(#addWaypoint, [point]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAll() => super.noSuchMethod(
    Invocation.method(#clearAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCameraMode() => super.noSuchMethod(
    Invocation.method(#toggleCameraMode, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> searchLocation(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLocation, [query]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> fetchRoute() =>
      (super.noSuchMethod(
            Invocation.method(#fetchRoute, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearRoute() => super.noSuchMethod(
    Invocation.method(#clearRoute, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
